src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $content;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/ArticleType.php
<?php
namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'タイトル',
                'attr' => ['class' => 'form-control']
            ])
            ->add('content', TextareaType::class, [
                'label' => '記事',
                'attr' => ['class' => 'form-control']
            ])
            ->add('created_at', DateType::class, [
                'label' => '日付'
            ])
            ->add('save', SubmitType::class, [
                'label'=>'投稿',
                'attr' => ['class' => 'btn btn-primary mt-2']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Knp\Component\Pager\PaginatorInterface;


class ArticleController extends AbstractController
{
    /**
     * 記事一覧を取得
     *
     * @param ArticleRepository $articleRepository
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $allArticleQuery = $articleRepository->createQueryBuilder('article');

        $article = $paginator->paginate(
            $allArticleQuery,
            $request->query->getInt('page', 1),
            3
        );

        return $this->render('article/index.html.twig', [
            'articles' => $article,
        ]);
    }

    /**
     * 記事投稿
     *
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * 記事取得
     *
     * @param Article $article
     * @Route("/{id}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * 記事を編集する
     *
     * @param Request $request
     * @param Article $article
     * @param EntityManagerInterface $entityManager
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * 記事を削除する
     *
     * @param Request $request
     * @param Article $article
     * @param EntityManagerInterface $entityManager
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('article_delete'.$article->getId(), $request->get('_delete_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('削除しますか？');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_delete_token" value="{{ csrf_token('article_delete' ~ article.id) }}">
    <button class="btn">削除する</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}記事編集{% endblock %}

{% block body %}
    <h1>記事編集</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>記事一覧</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>タイトル</th>
                <th>内容</th>
                <th>投稿日</th>
                <th>機能</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.content }}</td>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('article_show', {'id': article.id}) }}">見る</a>
                    <a href="{{ path('article_edit', {'id': article.id}) }}">編集</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">記事はありません</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation">
        {{ knp_pagination_render(articles) }}
    </div>

{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>記事を投稿する</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">戻る</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>記事</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>タイトル</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>内容</th>
                <td>{{ article.content }}</td>
            </tr>
            <tr>
                <th>投稿日</th>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('article_index') }}">戻る</a>

    <a href="{{ path('article_edit', {'id': article.id}) }}">編集する</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

        <style>
            li {
                list-style: none;
            }
            
            a {
                color: #333;
            }

            .pagination {
                display: inline-block;
            }

            .pagination a, .current {
                color: black;
                float: left;
                padding: 8px 16px;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <div class="header">
            <nav class="navbar navbar-dark bg-dark mt-3 mb-3 justify-content-center">
                <a href="{{ path('article_index') }}" class="navbar-brand">
                    ブログ
                </a>
                <ul class="navbar-nav mr-2">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('article_new') }}">記事投稿</a>
                    </li>
                </ul>
            </nav>
        </div>

        <div class="text-center">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>